Product.create ([
  {title: 'STANDARD TELECASTER', description: "For guitarists everywhere who appreciate great style, rich and versatile tone, and excellent value, the Standard Telecaster is an elegant and affordable classic with a great combination of traditional design and contemporary features. Time-honored Fender style and performance-minded modern upgrades don't have to break the bank, and this model delivers the best of both in an instrument ideal for Telecaster players everywhere at every level", image_url: 'http://www.samash.com/opncms/opencms/samash/galleries/landing-page-images/telecaster-landing-page/tele-beauty.jpg', price: 600},
  {title: 'MUSTANG 90', description: 'Perfect for garage rock and other styles that thrive on nonconformity, the Mustang 90 offers a distinctive take on a classic model. With upgraded features, unique aesthetics and fat Fender sound, this spirited instrument is perfect for players that march to a different beat. A new take on an underground classic, it stays true to the rebellious spirit that birthed rock n roll', image_url: 'https://cdn.shopify.com/s/files/1/0888/3684/products/0144033503_2_2048x2048.png?v=1508340044', price: 525},
  {title: 'STANDARD STRATOCASTER', description: "For guitarists everywhere who appreciate great style, rich and versatile tone, and excellent value, the Standard Stratocaster is an elegant and affordable classic with a great combination of traditional design and contemporary features. Time-honored Fender style and performance-minded modern upgrades don't have to break the bank, and this model delivers the best of both in an instrument ideal for Stratocaster players everywhere at every level", image_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Starcaster_model_stratocaster_by_fender.png',price: 600},
  {title: '1939 Steinway S', description: 'This traditional Steinway baby grand has a ebony case and an excellent original soundboard. It will be completely rebuilt using authentic Steinway parts and will be refinished in a hand rubbed satin ebony finish. Comes with a matching artist bench.', image_url: 'http://www.steinway.com/.imaging/mte/steinway-us-theme/Large-Rectangle/dam/pianos/Boston/Grands/Landscape/BostonPE_GP193EP_fma_scale.jpg/jcr:content/BostonPE_GP193EP_fma_scale.jpg',price: 36000},
  {title: 'Pearl Export EXL 5-Piece Drum Set w/ Hardware', description: "The Pearl Export is one of the most popular drum sets of all time, and for good reason. The Export manages to combine quality craftsmanship with ground breaking affordability to give drummers what they really want, an outstanding kit that won't break the bank. Pearl continues to deliver with these new Exports, which feature some major upgrades compared to it's predecessor.", image_url: 'http://pearldrum.com/common/assets/images/drumsets/export-EXL/EXL725C246%20Export%20Lacquer%20246%20Natural%20Cherry.jpg',price: 789}])

  User.create([
    {id:1, first: 'Lisa', last: 'Mae', email: 'lisamae@example.com', password: 'test'},
    {id:2, first: 'Tom', last: 'Petty', email: 'tpetty@example.com', password: 'test'},
    {id:3, first: 'Michael', last: 'Jackson', email: 'mj@example.com', password: 'test'}
    ])
